#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=RunSliceGPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=/home/scur1769/ALMA-Matters/utils/outputs/RunSliceGPT_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate DL4_env

python -uc "import torch; print('GPU available?', torch.cuda.is_available())"

cd $HOME/ALMA-Matters

python compression/pruning/TransformerCompression/experiments/run_slicegpt.py \
        --model "haoranxu/ALMA-7B" \
        --save-dir $HOME/ALMA-Matters/models/ \
        --sparsity 0.05 \
        --device "cuda" \
        --no-wandb \
        --eval-baseline \
        # --model "meta-llama/Llama-2-7B-hf" \
