#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=RunSliceGPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=/home/scur1769/ALMA-Matters/utils/script_outputs/RunSliceGPT_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate DL4_env

cd $HOME/ALMA-Matters/compression/pruning/TransformerCompression/experiments

echo "+++Directory: $(pwd)"

python run_slicegpt.py \
        --model "haoranxu/ALMA-7B" \
        --save-dir $HOME/ALMA-Matters/models/ \
        --sparsity 0.25 \
        --device "cuda:0" \
        --eval-baseline \
        --no-wandb

