#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=RunExample
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=/home/scur1769/ALMA-Matters/utils/outputs/RunExample_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/ALMA-Matters

source activate DL4_env

python -uc "import torch; print('GPU available?', torch.cuda.is_available())"

python utils/run_example.py