#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=FinetuneSliceGPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=/home/scur1769/ALMA-Matters/utils/outputs/FinetuneSliceGPT_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate DL4_env

python -uc "import torch; print('GPU available?', torch.cuda.is_available())"
python --version

cd $HOME/ALMA-Matters

sparsity=0.10

python compression/pruning/TransformerCompression/experiments/run_finetuning.py \
        --model "haoranxu/ALMA-7B" \
        --sliced-model-path "models" \
        --sparsity $sparsity \
        --save-dir $HOME/ALMA-Matters/models/ft \
        --st_checkpoint_dir $HOME/ALMA-Matters/models/ft \
        --no-wandb \
        --early-stopping-patience 1000000 \
        --device "cuda" \
        --ppl-eval-dataset "alpaca" \
        --finetune-dataset "alpaca" \
        --finetune-train-nsamples 8000 \
        --finetune-train-batch-size 2 \
        --finetune-train-seqlen 1024 \
        --finetune-test-nsamples 128 \
        --finetune-test-batch-size 2 \
        --finetune-test-seqlen 1024

echo "Finished finetuning SliceGPT with sparsity $sparsity"